### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LReiz** [LReiz/Anime-Editor#1]
- [x] Robô Pre-processador
     - [x] Criar pastas temporárias das imagens e do áudio (para a edição)
     - [x] Separar o Áudio do Vídeo
     - [x] Converter Vídeo para mp4
     - [x] Diminuir o FPS do vídeo
     - [x] Extrair os frames do vídeo e colocá-las na pasta de frames
- [x] Robô para áudio
     - [x] ML para classificar trechos de áudio
     - [x] Pré-processamento do áudio analisado
     - [x] Classificar os trechos de um vetor de áudio
     - [x] Encontrar agrupamentos no vetor de áudio
     - [x] Determinar o início e a duração de um trecho em segundos (a partir do vetor e do sr escolhido)
- [ ] Robô para imagem
     - [ ] Treinar o ML da IBM com as imagens
     - [x] Diminuir o FPS do vídeo
     - [x] Colocar os frames da pasta de frames em um vetor
     - [ ] Classificar as imagens do vetor de frames
     - [ ] Determinar o início e a duração do trecho de "vídeo" classificado em segundos (a partir do vetor e do FPS escolhido)
     - [ ] Determinar posição e tamanho do objeto encontrado na imagem
- [ ] Robô para edição do Vídeo
     - [ ] Criar uma cópia do vídeo original
     - [ ] Criar pasta temporária para imagens do vídeo
     - [ ] Separar o frames da cópia do vídeo e colocá-lo na pasta acima
     - [ ] Marcar os frames com imagens pre-selecionadas de acordo com os valores retornados pelo Robô de Imagem
     - [ ] Juntar o frames em um vídeo
     - [ ] Substituir trechos do vídeo com base no áudio
- [x] Robô para edição do áudio
     - [x] Criar pasta temporária para os trechos de áudio do vídeo
     - [x] Cortar o áudio de acordo com os valores retornados pelo Robô de Áudio (início e duração)
     - [x] Substituir trechos determinados por áudio pré-selecionados de mesma duração
     - [x] Juntar todos os áudios em um
- [ ] Robô Apresentador
     - [x] Unir áudio com vídeo
     - [x] Salvar resultado final
     - [ ] Apagar as pastas temporárias
- [x] Megazord
     - [x] Conectar todos os Robôs (executar o programa em um só comando)
